In [ ]:
import pandas as pd
import numpy as np
import re
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
# impoting kaggle key or api
!mkdir -p ~/.kaggle
!cp /content/drive/MyDrive/kaggle/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

Mounted at /content/drive

In [ ]:
!kaggle datasets download -d mattimansha/inspirational-quotes

Dataset URL: https://www.kaggle.com/datasets/mattimansha/inspirational-quotes
License(s): CC-BY-SA-4.0
Downloading inspirational-quotes.zip to /content
  0% 0.00/139k [00:00<?, ?B/s]
100% 139k/139k [00:00<00:00, 476MB/s]

In [ ]:
!unzip '/content/inspirational-quotes.zip'

Archive:  /content/inspirational-quotes.zip
  inflating: insparation.csv

In [ ]:
import pandas as pd
df=pd.read_csv('/content/insparation.csv')
df.head()

,Unnamed: 0,Category,Quote,Image-link,Quote-url
0,0,LOVE,Let us see what love can do.,https://assets.passiton.com/quotes/quote_artwo...,/inspirational-quotes/6900-let-us-see-what-lov...
1,1,LOVE,We can’t heal the world today. But we can begi...,https://assets.passiton.com/quotes/quote_artwo...,/inspirational-quotes/8169-we-can-t-heal-the-w...
2,2,LISTENING,Listen with curiosity. Speak with honesty. Act...,https://assets.passiton.com/quotes/quote_artwo...,/inspirational-quotes/8083-listen-with-curiosi...
3,3,LISTENING,The most basic and powerful way to connect to ...,https://assets.passiton.com/quotes/quote_artwo...,/inspirational-quotes/7139-the-most-basic-and-...
4,4,LISTENING,"Knowledge speaks, but wisdom listens.",https://assets.passiton.com/quotes/quote_artwo...,/inspirational-quotes/8376-knowledge-speaks-bu...

In [ ]:
df = df[["Category", "Quote"]]
df = df.dropna()
df["Category"] = df["Category"].str.lower()

In [ ]:
df.head()

    Category                                              Quote
0       love                      Let us see what love can do.
1       love  We can’t heal the world today. But we can begi...
2  listening  Listen with curiosity. Speak with honesty. Act...
3  listening  The most basic and powerful way to connect to ...
4  listening             Knowledge speaks, but wisdom listens.

In [ ]:
text_data = []

for i in range(len(df)):
    category = df["Category"].iloc[i]
    quote = df["Quote"].iloc[i]
    combined = category + " " + quote
    text_data.append(combined.lower())

In [ ]:
cleaned_text = []

for line in text_data:
    line = re.sub(r'[^a-zA-Z\s]', '', line)  # remove punctuation
    cleaned_text.append(line)

In [ ]:
VOCAB_SIZE = 5000
MAX_SEQ_LEN = 25

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(cleaned_text)

print("Vocabulary size:", VOCAB_SIZE)

Vocabulary size: 5000

In [ ]:
input_sequences = []
for line in cleaned_text:
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)
# Pad sequences
input_sequences = pad_sequences(
    input_sequences,
    maxlen=MAX_SEQ_LEN,
    padding='pre'
)
# Split into x and y
x = input_sequences[:, :-1]
y = input_sequences[:, -1]

print("Total training samples:", len(x))

Total training samples: 35988

In [ ]:
model = Sequential()
model.add(Embedding(VOCAB_SIZE, 128, input_length = MAX_SEQ_LEN-1))
model.add(LSTM(256, return_sequences=True))
model.add(LSTM(128))
model.add(Dropout(0.4))
model.add(Dense(VOCAB_SIZE, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
early_stop = EarlyStopping(monitor='loss', patience = 5)

history = model.fit(x, y, epochs=200, batch_size=128, callbacks=[early_stop])

Epoch 1/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 12s 13ms/step - accuracy: 0.0401 - loss: 6.8446
Epoch 2/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0530 - loss: 6.2384
Epoch 3/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0528 - loss: 6.1199
Epoch 4/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.0612 - loss: 5.9777
Epoch 5/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.0719 - loss: 5.8739
Epoch 6/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0842 - loss: 5.7483
Epoch 7/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0889 - loss: 5.6631
Epoch 8/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.0999 - loss: 5.5666
Epoch 9/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.1057 - loss: 5.4684
Epoch 10/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1121 - loss: 5.3849
Epoch 11/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1189 - loss: 5.3096
Epoch 12/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1245 - loss: 5.2308
Epoch 13/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.1309 - loss: 5.1620
Epoch 14/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.1373 - loss: 5.0969
Epoch 15/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1386 - loss: 5.0374
Epoch 16/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1429 - loss: 4.9759
Epoch 17/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.1430 - loss: 4.9795
Epoch 18/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1468 - loss: 4.8723
Epoch 19/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1550 - loss: 4.8036
Epoch 20/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1594 - loss: 4.7187
Epoch 21/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.1589 - loss: 4.6725
Epoch 22/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.1655 - loss: 4.5946
Epoch 23/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1679 - loss: 4.5342
Epoch 24/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1710 - loss: 4.4733
Epoch 25/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.1772 - loss: 4.4161
Epoch 26/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1773 - loss: 4.3707
Epoch 27/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1845 - loss: 4.3228
Epoch 28/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1881 - loss: 4.2696
Epoch 29/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.1914 - loss: 4.2093
Epoch 30/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.1987 - loss: 4.1467
Epoch 31/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1986 - loss: 4.0953
Epoch 32/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2073 - loss: 4.0476
Epoch 33/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.2098 - loss: 3.9930
Epoch 34/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.2123 - loss: 3.9540
Epoch 35/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2218 - loss: 3.8812
Epoch 36/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2288 - loss: 3.8333
Epoch 37/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.2307 - loss: 3.7911
Epoch 38/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.2382 - loss: 3.7357
Epoch 39/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2460 - loss: 3.6943
Epoch 40/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2463 - loss: 3.6552
Epoch 41/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2590 - loss: 3.5921
Epoch 42/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.2645 - loss: 3.5428
Epoch 43/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2709 - loss: 3.4905
Epoch 44/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2795 - loss: 3.4561
Epoch 45/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.2827 - loss: 3.4095
Epoch 46/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.2888 - loss: 3.3758
Epoch 47/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.2983 - loss: 3.3181
Epoch 48/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.3066 - loss: 3.2698
Epoch 49/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3104 - loss: 3.2367
Epoch 50/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.3220 - loss: 3.1792
Epoch 51/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3266 - loss: 3.1543
Epoch 52/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3323 - loss: 3.1053
Epoch 53/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3420 - loss: 3.0737
Epoch 54/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.3423 - loss: 3.0359
Epoch 55/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.3584 - loss: 2.9630
Epoch 56/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3561 - loss: 2.9637
Epoch 57/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3629 - loss: 2.9126
Epoch 58/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.3699 - loss: 2.8662
Epoch 59/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.3752 - loss: 2.8297
Epoch 60/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3794 - loss: 2.8026
Epoch 61/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3911 - loss: 2.7561
Epoch 62/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.3930 - loss: 2.7511
Epoch 63/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.4012 - loss: 2.7012
Epoch 64/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4069 - loss: 2.6630
Epoch 65/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4135 - loss: 2.6273
Epoch 66/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4213 - loss: 2.5849
Epoch 67/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.4261 - loss: 2.5602
Epoch 68/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4328 - loss: 2.5260
Epoch 69/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4352 - loss: 2.5046
Epoch 70/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4421 - loss: 2.4656
Epoch 71/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.4503 - loss: 2.4385
Epoch 72/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.4507 - loss: 2.4166
Epoch 73/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4581 - loss: 2.3747
Epoch 74/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4687 - loss: 2.3439
Epoch 75/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.4753 - loss: 2.3267
Epoch 76/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.4789 - loss: 2.2778
Epoch 77/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4861 - loss: 2.2469
Epoch 78/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4858 - loss: 2.2334
Epoch 79/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.4897 - loss: 2.2298
Epoch 80/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.4958 - loss: 2.1763
Epoch 81/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4983 - loss: 2.1534
Epoch 82/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5090 - loss: 2.1204
Epoch 83/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5087 - loss: 2.1269
Epoch 84/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.5140 - loss: 2.0853
Epoch 85/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5208 - loss: 2.0521
Epoch 86/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5271 - loss: 2.0396
Epoch 87/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.5284 - loss: 2.0057
Epoch 88/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.5338 - loss: 2.0009
Epoch 89/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5491 - loss: 1.9431
Epoch 90/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5438 - loss: 1.9487
Epoch 91/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5480 - loss: 1.9131
Epoch 92/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.5565 - loss: 1.9024
Epoch 93/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5550 - loss: 1.8772
Epoch 94/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5562 - loss: 1.8736
Epoch 95/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5615 - loss: 1.8332
Epoch 96/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.5728 - loss: 1.8026
Epoch 97/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.5767 - loss: 1.7935
Epoch 98/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5727 - loss: 1.7915
Epoch 99/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5835 - loss: 1.7531
Epoch 100/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.5839 - loss: 1.7346
Epoch 101/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5862 - loss: 1.7145
Epoch 102/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5990 - loss: 1.6742
Epoch 103/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5998 - loss: 1.6726
Epoch 104/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6000 - loss: 1.6752
Epoch 105/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6033 - loss: 1.6566
Epoch 106/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6098 - loss: 1.6469
Epoch 107/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.6120 - loss: 1.6105
Epoch 108/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6208 - loss: 1.5967
Epoch 109/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6150 - loss: 1.5989
Epoch 110/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6267 - loss: 1.5465
Epoch 111/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6299 - loss: 1.5352
Epoch 112/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6293 - loss: 1.5180
Epoch 113/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6334 - loss: 1.5219
Epoch 114/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6335 - loss: 1.5129
Epoch 115/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6339 - loss: 1.5056
Epoch 116/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6395 - loss: 1.4893
Epoch 117/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6471 - loss: 1.4502
Epoch 118/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6543 - loss: 1.4267
Epoch 119/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6506 - loss: 1.4360
Epoch 120/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6544 - loss: 1.4173
Epoch 121/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6608 - loss: 1.3886
Epoch 122/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6626 - loss: 1.3833
Epoch 123/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6617 - loss: 1.3870
Epoch 124/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6658 - loss: 1.3546
Epoch 125/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.6684 - loss: 1.3486
Epoch 126/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6750 - loss: 1.3354
Epoch 127/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6712 - loss: 1.3260
Epoch 128/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.6781 - loss: 1.3150
Epoch 129/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6855 - loss: 1.2816
Epoch 130/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6782 - loss: 1.2981
Epoch 131/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6875 - loss: 1.2791
Epoch 132/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.6890 - loss: 1.2739
Epoch 133/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6881 - loss: 1.2618
Epoch 134/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6933 - loss: 1.2456
Epoch 135/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6935 - loss: 1.2351
Epoch 136/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.6953 - loss: 1.2342
Epoch 137/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6984 - loss: 1.2182
Epoch 138/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7061 - loss: 1.1867
Epoch 139/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7020 - loss: 1.1973
Epoch 140/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7007 - loss: 1.1920
Epoch 141/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7029 - loss: 1.1785
Epoch 142/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7148 - loss: 1.1557
Epoch 143/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7087 - loss: 1.1563
Epoch 144/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7142 - loss: 1.1387
Epoch 145/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7132 - loss: 1.1459
Epoch 146/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7156 - loss: 1.1250
Epoch 147/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7227 - loss: 1.1091
Epoch 148/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7253 - loss: 1.0953
Epoch 149/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7229 - loss: 1.1077
Epoch 150/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7270 - loss: 1.0871
Epoch 151/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7316 - loss: 1.0854
Epoch 152/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7357 - loss: 1.0603
Epoch 153/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7329 - loss: 1.0733
Epoch 154/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7311 - loss: 1.0628
Epoch 155/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7343 - loss: 1.0436
Epoch 156/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7320 - loss: 1.0588
Epoch 157/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7337 - loss: 1.0545
Epoch 158/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7436 - loss: 1.0262
Epoch 159/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7412 - loss: 1.0134
Epoch 160/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7439 - loss: 1.0175
Epoch 161/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - accuracy: 0.7490 - loss: 1.0063
Epoch 162/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7477 - loss: 0.9958
Epoch 163/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7531 - loss: 0.9916
Epoch 164/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - accuracy: 0.7560 - loss: 0.9712
Epoch 165/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - accuracy: 0.7536 - loss: 0.9663
Epoch 166/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7535 - loss: 0.9763
Epoch 167/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7559 - loss: 0.9687
Epoch 168/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.7609 - loss: 0.9510
Epoch 169/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.7548 - loss: 0.9533
Epoch 170/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step - accuracy: 0.7576 - loss: 0.9495
Epoch 171/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - accuracy: 0.7591 - loss: 0.9517
Epoch 172/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7618 - loss: 0.9346
Epoch 173/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7667 - loss: 0.9259
Epoch 174/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7596 - loss: 0.9327
Epoch 175/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7649 - loss: 0.9153
Epoch 176/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7657 - loss: 0.9127
Epoch 177/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7695 - loss: 0.9079
Epoch 178/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.7748 - loss: 0.8755
Epoch 179/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7717 - loss: 0.8874
Epoch 180/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7694 - loss: 0.8822
Epoch 181/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7745 - loss: 0.8848
Epoch 182/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7788 - loss: 0.8681
Epoch 183/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.7799 - loss: 0.8647
Epoch 184/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7808 - loss: 0.8624
Epoch 185/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7773 - loss: 0.8718
Epoch 186/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7842 - loss: 0.8522
Epoch 187/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7790 - loss: 0.8653
Epoch 188/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7732 - loss: 0.8749
Epoch 189/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7850 - loss: 0.8309
Epoch 190/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7802 - loss: 0.8472
Epoch 191/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7819 - loss: 0.8464
Epoch 192/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7835 - loss: 0.8310
Epoch 193/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7862 - loss: 0.8329
Epoch 194/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7843 - loss: 0.8388
Epoch 195/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7897 - loss: 0.8036
Epoch 196/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7840 - loss: 0.8409
Epoch 197/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7916 - loss: 0.8066
Epoch 198/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7937 - loss: 0.8119
Epoch 199/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.7968 - loss: 0.7861
Epoch 200/200
282/282 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.8003 - loss: 0.7757

In [ ]:
# Save trained model
model.save("quote_model.h5")
# Save tokenizer
import pickle
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)
print("Model and tokenizer saved.")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model and tokenizer saved.

In [ ]:
from tensorflow.keras.models import load_model
# Load model
model = load_model("quote_model.h5")
# Load tokenizer
with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)
# Reverse mapping
index_to_word = {index: word for word, index in tokenizer.word_index.items()}
max_seq_len = 25

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
def sample(preds, temperature=0.7):
    preds = np.asarray(preds).astype("float64")
    preds = np.log(preds + 1e-8) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    return np.random.choice(len(preds), p=preds)

In [ ]:
def generate_quote(seed_text, next_words=25, temperature=0.7):
    seed_text = seed_text.lower()
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences(
            [token_list],
            maxlen=max_seq_len - 1,
            padding='pre'
        )
        predictions = model.predict(token_list, verbose=0)[0]
        predicted_index = sample(predictions, temperature)
        next_word = index_to_word.get(predicted_index)
        if not next_word:
            break
        seed_text += " " + next_word
    return seed_text

In [ ]:
print(generate_quote("success", next_words=25, temperature=0.7))

success for every day we can choose it for every light practice there is a great act of our children and have a thing that love

In [ ]:
print(generate_quote("love", next_words=25, temperature=0.7))

love my success of your dreams make a difference but nothing can be better to have it in them and do or any experience or know

In [ ]:
print(tf.__version__)

2.19.0

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=quote_model.pkl.